# Generated by Django 4.1.4 on 2022-12-29 21:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='SPUnameOfGoods')),
                ('detail', ckeditor.fields.RichTextField(blank=True, verbose_name='detail')),
            ],
            options={
                'verbose_name': 'GoodsSPU',
                'verbose_name_plural': 'GoodsSPU',
                'db_table': 'df_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='Name of Goods')),
                ('desc', models.CharField(max_length=300, verbose_name='Description of Goods')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Goods Price')),
                ('unite', models.CharField(max_length=20, verbose_name='Unite of Goods')),
                ('image', models.ImageField(upload_to='goods', verbose_name='image of goods')),
                ('stock', models.IntegerField(default=1, verbose_name='The Stock of Goods')),
                ('sales', models.IntegerField(default=0, verbose_name='Goods Sales')),
                ('status', models.SmallIntegerField(choices=[(0, 'OffStock'), (1, 'InStock')], default=1, verbose_name='The Status of Good')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='goodsSPU')),
            ],
            options={
                'verbose_name': 'goods',
                'verbose_name_plural': 'goods',
                'db_table': 'df_goods_sku',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='TypeName')),
                ('logo', models.CharField(max_length=20, verbose_name='logo')),
                ('image', models.ImageField(upload_to='type', verbose_name='ImageType')),
            ],
            options={
                'verbose_name': 'Type of Goods',
                'verbose_name_plural': 'Type of Goods',
                'db_table': 'df_goods_type',
            },
        ),
        migrations.CreateModel(
            name='IndexPromotionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='Name of Activity')),
                ('url', models.URLField(verbose_name='Link of activity')),
                ('image', models.ImageField(upload_to='banner', verbose_name='The activity image')),
                ('index', models.SmallIntegerField(default=0, verbose_name='Oder of display')),
            ],
            options={
                'verbose_name': 'Homepage Promotions',
                'verbose_name_plural': 'Homepage Promotions',
                'db_table': 'df_index_promotion',
            },
        ),
        migrations.CreateModel(
            name='IndexTypeGoodsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('display_type', models.SmallIntegerField(choices=[(0, 'Title'), (1, 'Image')], default=1, verbose_name='Displayed Type')),
                ('index', models.SmallIntegerField(default=0, verbose_name='Displayed order')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodssku', verbose_name='GoodsSKU')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodstype', verbose_name='Type of Goods')),
            ],
            options={
                'verbose_name': 'Home Category Display Products',
                'verbose_name_plural': 'Home Category Display Products',
                'db_table': 'df_index_type_goods',
            },
        ),
        migrations.CreateModel(
            name='IndexGoodsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('image', models.ImageField(upload_to='banner', verbose_name='Image')),
                ('index', models.SmallIntegerField(default=0, verbose_name='the display order')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodssku', verbose_name='Goods')),
            ],
            options={
                'verbose_name': 'Carousel Goods',
                'verbose_name_plural': 'Carousel Goods',
                'db_table': 'df_index_banner',
            },
        ),
        migrations.AddField(
            model_name='goodssku',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodstype', verbose_name='GoodType'),
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('image', models.ImageField(upload_to='goods', verbose_name='ImagePath')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodssku', verbose_name='Goods')),
            ],
            options={
                'verbose_name': 'The image of goods',
                'verbose_name_plural': 'The image of goods',
                'db_table': 'df_goods_image',
            },
        ),
    ]
