# Generated by Django 4.1.4 on 2022-12-29 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Address'},
        ),
        migrations.AlterField(
            model_name='address',
            name='addr',
            field=models.CharField(max_length=256, verbose_name='Receiver Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is Default'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='TEL'),
        ),
        migrations.AlterField(
            model_name='address',
            name='receiver',
            field=models.CharField(max_length=20, verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Account Belong'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=6, null=True, verbose_name='Zipcode'),
        ),
    ]
