"""
Django settings for dailyFresh project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import sys





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#print(BASE_DIR.as_posix())
#后面加的

STATICFILES_DIRS = [
os.path.join(BASE_DIR, "static"),
]

"""

BASE_DIR 是一个变量，它的值是当前文件（也就是 Python 文件）所在目录的父目录的父目录的路径。

这里的 __file__ 是 Python 的内置变量，它的值是当前文件的路径。

Path(__file__).resolve() 获取当前文件的绝对路径。

parent 属性可以获取父目录的路径，.parent.parent 则是获取父目录的父目录的路径。

所以 BASE_DIR = Path(__file__).resolve().parent.parent 的意思是：将当前文件的绝对路径解析出来，然后获取它的父目录的父目录的路径，最后将这个路径赋值给 BASE_DIR 变量
"""

sys.path.insert(0, os.path.join(BASE_DIR,'apps'))
#This way we are telling Django to use our custom model instead the default one.
AUTH_USER_MODEL='user.User'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q@o)nu9c=s5i$m+uzk37_ok=v^l@t8ch=b*nzd=+(7b%z#0zba'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', #配置静态文件
    'apps.user',
    'apps.goods',
    'apps.cart',
    'apps.order',
    'ckeditor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dailyFresh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dailyFresh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Settings to send email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Server address of SMTP
EMAIL_HOST = 'smtp.163.com'
#SMTP PORT
EMAIL_PORT=25
#发送邮件的邮箱
EMAIL_HOST_USER = 'mydailyfresh@163.com'
# The client authorization password set in the mailbox
EMAIL_HOST_PASSWORD = ''
#收件人看到的发件人
EMAIL_FROM = 'DailyFresh<mydailyfresh@163.com>'

CELERY_BROKER_URL = 'redis://localhost:6379/0'


# Django的缓存配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# 配置session存储
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
